# Site settings
title: SRS Design Team
email: mecolmg@vt.edu
description: >
  The SRS Design Team is a team of students at Virginia Tech
  who are dedicated to solving the issue of space debris, by
  developing a spaceplane which can fly to low earth orbit and 
  recover decaying satellites.
baseurl: ""
url: ""
fixedNav: 'true' # true or false
theme: blue # green, blue, orange, purple, grey
twitterUsername: 
githubUsername: SRSTeam
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:day/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
github:
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate